name: Deploy

env:
  VITE_API_KEY: ${{ secrets.VITE_API_KEY }}

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      # Step 4: Build the project with environment variable
      - name: Build project
        run: VITE_API_KEY=${{ secrets.VITE_API_KEY }} npm run build

      # Step 5: Upload production-ready build files as an artifact
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Download the build artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
